config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'setup_chat#index'

  resources :setup_chat, only: [:index, :create] do
    post '/register_user' => 'setup_chat#register_user'
  end

  resources :chat, only: [:index] do
    get '/all_messages' => 'chat#all_messages'
  end

  resources :message, only: [:index, :create] do
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/message_wrapper.rb
class MessageWrapper
  attr_reader :body,
              :created_at,
              :direction,
              :sender

  def initialize(
    body:,
    created_at:,
    direction:,
    sender:
  )
    @body = body
    @created_at = created_at
    @direction = direction
    @sender = sender
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ActionController::Base
  def index
    render 'chatroom'
  end
end

app/controllers/message_controller.rb
class MessageController < ActionController::Base

  def index
    respond_with_message(message_service.get_conversation_history)
  end

  def create
    respond_with_message(message_service.create_new_message(params['body']))
  end

  private

  def respond_with_message(messages)
    ret = {}
    ret[:json] = messages
    ret[:each_serializer] = MessageSerializer
    render ret
  end

  def message_service
    @message_service ||= MessageService.new(session)
  end

end

app/controllers/setup_chat_controller.rb
class SetupChatController < ActionController::Base

  layout 'application'

  def index
    render 'username'
  end

  def create
    start_chat
  end

  def register_user
    run_register_rake_task
    redirect_to root_url and return  
  end

  def start_chat
    if validate(username, friend)
      redirect_to chat_index_url and return
    else
      redirect_to root_url and return  
    end
  end

  def validate(username, friend_username)
    info = chat_validation_service.get_both_user_info(username, friend_username)
    message = ''

    if not info[:friend][:message].empty?
      message = "#{info[:friend][:message]}"
      flash[:error] = message
      return false
    end

    flash[:error] = ''
    session[:my_username] = username
    session[:friend_username] = friend_username
    session[:my_id] = info[:myself][:user_id]
    session[:friend_id] = info[:friend][:user_id]
    return true
  end

  def run_register_rake_task
    %x[rake registration:create_new_user[#{params[:users][:new_user]}]]
  end

  private

  def chat_validation_service
    @chat_validation_service ||= ChatValidationService.new(User.all.to_a)
  end

  def username
    params[:users][:username]
  rescue
    nil
  end

  def friend
    params[:users][:friend]
  rescue
    nil
  end
end

app/views/chat/chatroom.slim
= javascript_include_tag 'application'

.messagingContainer
  .messaging
    .messaging-header
      strong Chat with your friend
    .messaging-history
      ul.messages-container
        .hide
          li
    /! end messaging-history
    .
      textarea.messaging-textArea placeholder="Message your friend"
      button.btn.is-sendingMessage Send
    /! end chat-message
  /! end chat

app/views/layouts/application.slim
doctype html
html
  main
    = yield
  body
    - if flash[:error]
      .alert-box.u-background--alert
        = flash[:error]
    - if flash[:success]
      .alert-box.u-background--success
        i.fa.fa-check.u-hMargin
        = flash[:success]

app/views/setup_chat/username.slim
div.row
  = form_for :users, url: setup_chat_index_path() do |form|
    td
      = form.label :username, id: "#new-name"
      = form.text_field :username, id: "#new-name"
    br
    td
      = form.label :friend, id: "#new-name"
      = form.text_field :friend, id: "#new-name"

    = form.submit "Go to Chat", class: 'button'

br
br
br

div.row
  = form_for :users, url: setup_chat_register_user_path(1) do |form|
    td
      = form.label 'Register a new User before getting started'   , id: "#register-name"
      = form.text_field :new_user, id: "#register-name"

    = form.submit "Save!", class: 'button'